version: '3.8'

services:
  server-service:
    image: go-grpc-demo-server:latest
    build: .
    ports:
      - "50051:50051"
    networks:
      - train-network
  
  client-service:
      build: .
      image: go-grpc-demo-client:latest
      depends_on:
        - server-service
      environment:
        - SERVER_ADDRESS=server-service:50051
      networks:
        - train-network    

networks:
  train-network:
    driver: bridge
